language: java

install:
 - gradle assemble
 - sudo ./gradlew assemble

before_install:
 - chmod +x gradlew

script:
 - gradle check
 - ./gradlew check

android:
 components:
   - build-tools-26.1.1
   - android-26
   - sys-img-armeabi-v7a-android-tv-l
   - add-on
   - extra
   - tools
   - platform-tools
   - tools
 licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+